### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269** [hashgraph/fabric-samples-hcs#42]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by PavelSBorisov** [comment]
Repo's CODEOWNERS file is outdated, and is in root directory - need to check how it should be updated.

**Comment by PavelSBorisov** [comment]
Repo seems to have no significant activity in the last 3-4 years, @andrewb1269hg can you take a look and let me know if this issue should be closed?

**Comment by andrewb1269** [comment]
Will not do.
